### ISSUE TITLE
when i import lib to my nextjs

### ISSUE THREAD

**Issue by fah-iiv** [TaqBostan/react-image-label#4]
Internal error: TypeError: Cannot read properties of null (reading 'createElementNS')
    at create (./node_modules/react-svgdotjs/node_modules/@svgdotjs/svg.js/src/utils/adopter.js:33:73)
    at nodeOrNew (./node_modules/react-svgdotjs/node_modules/@svgdotjs/svg.js/src/utils/adopter.js:65:103)
    at new Svg (./node_modules/react-svgdotjs/node_modules/@svgdotjs/svg.js/src/elements/Svg.js:20:71)
    at makeInstance (./node_modules/react-svgdotjs/node_modules/@svgdotjs/svg.js/src/utils/adopter.js:44:12)
    at eval (./node_modules/react-svgdotjs/dist/index.js:1:1092)
    at Object.oN [as useMemo] (/home/iiv030/Documents/my-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:12:68806)
    at t.useMemo (/home/iiv030/Documents/my-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:162732)
    at c (./node_modules/react-svgdotjs/dist/index.js:1:1064)
    at au (/home/iiv030/Documents/my-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:10446)
    at /home/iiv030/Documents/my-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:15122
    at aw (/home/iiv030/Documents/my-app/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:169

**Comment by fah-iiv** [comment]
just doing this

```
'use client';

import React, { useState, useEffect, useRef } from 'react';
import { ImageAnnotator, useImageAnnotator } from 'react-image-label';


const Component = () => {
  const { setHandles, annotator } = useImageAnnotator();

  return (
    <div className="container-fluid">

<ImageAnnotator
  setHandles={setHandles}
  naturalSize={true}
  imageUrl={"https://xxx.jpeg"}
  onReady={annotator => { annotator.drawRectangle() }} />
    </div>
  );
};

export default Component;
```

**Comment by TaqBostan** [comment]
Hi,

Sorry for the problem you mentioned. Please install version 1.2.2 and let me know if everything is working fine in your Next.js project.

**Comment by fah-iiv** [comment]
it solved
