### ISSUE TITLE
How to save shapes and restore them?

### ISSUE THREAD

**Issue by CesarCruzUtec** [TaqBostan/react-image-label#8]
I'm currently using this package, and it's working great, but I have a couple of questions. When I finish defining the shapes in an image, I save only the category and the points list to store them in a database. Later, I retrieve this data to rebuild the shapes. However, I don't see a clear way to do this right now. Is there a constructor or method to recreate the shapes so the annotator can continue using them for adding, modifying, or deleting?

**Comment by TaqBostan** [comment]
Hi,

To save the shapes you have drawn, call `annotator.getShapes()` to get detailed information. 

To rebuild them on load, use `shapes` prop. This way you can use the same data you have received from `annotator.getShapes()` (see [raw data](https://codesandbox.io/p/sandbox/f2gnwn?file=%2Fsrc%2Fdata.js%3A52%2C12-52%2C19)). As an alternative, each shape has an exclusive constructor for instantiation (see [typed data](https://codesandbox.io/p/sandbox/r9mw79?file=%2Fsrc%2Fdata.js%3A1%2C38-1%2C45)). As you can infer from the constructors ([Polygon and Rectangle](https://github.com/TaqBostan/react-image-label/blob/ac8e4b6484c7e6f0310562f81f6d8525e9dcb0b4/src/base/types.ts#L85), [Circle](https://github.com/TaqBostan/react-image-label/blob/ac8e4b6484c7e6f0310562f81f6d8525e9dcb0b4/src/base/types.ts#L172), and [Ellipse](https://github.com/TaqBostan/react-image-label/blob/ac8e4b6484c7e6f0310562f81f6d8525e9dcb0b4/src/base/types.ts#L194)), some arguments are optional. For example, if you do not use colorful shapes, ignore `color`. 

Check out [demo 1](https://f2gnwn.csb.app/) and [demo 2](https://r9mw79.csb.app/) for some examples.

**Comment by CesarCruzUtec** [comment]
Thanks for your response! I have another question I forgot to include earlier.

In the annotator component, one of the props is shapes, which accepts a list of shapes to display. In my web app, I have a dropdown menu that selects a category, and I want the image to show only the shapes that belong to the selected category. I have a variable that holds these filtered shapes, and it updates whenever I change the category.

The issue is that the annotator component doesn’t update dynamically. To see the updated shapes, I currently need to close and reopen a modal, which is inconvenient. I tried adding a key prop to the annotator component, hoping it would re-render on updates, but this causes both the annotator and the variable to reset, resulting in the loss of all data.

Do you have any suggestions for resolving this?

**Comment by TaqBostan** [comment]
I added `shapes` to my dependency array. So if you `setState` it, the component will update. Please install version 1.3.6 and let me know if everything is working fine.

**Comment by CesarCruzUtec** [comment]
I recently updated the package, and it seems to be working overall, but I encountered an issue when switching between image pages or selected categories.

Here’s what happens:

1. I create a rectangle on the first image while the first category is selected, and it works as expected.
2. When I switch to another category, the shapes are cleared, which is also expected. However, when I draw a new rectangle in the second category, it doesn’t associate with the selected category.
3. If I switch back to the first category, I can see the rectangle I previously created. But when I return to the second category, I encounter an error message.

> EditionPage.js:86 ingredients
> EditionPage.js:87 0
> index.tsx:16 Uncaught TypeError: Cannot read properties of undefined (reading 'type')
>     at index.tsx:16:1
>     at Array.filter (<anonymous>)
>     at s (index.tsx:16:1)
>     at Image.d (index.tsx:103:1)
>     at Image.<anonymous> (Image.js:38:1)
> (anonymous) @ index.tsx:16
> s @ index.tsx:16
> d @ index.tsx:103
> (anonymous) @ Image.js:38
> load
> (anonymous) @ event.js:54
> on @ event.js:42
> load @ Image.js:22
> (anonymous) @ Image.js:72
> (anonymous) @ adopter.js:137
> (anonymous) @ index.tsx:109
> (anonymous) @ index.tsx:126
> commitHookEffectListMount @ react-dom.development.js:23189
> commitPassiveMountOnFiber @ react-dom.development.js:24965
> commitPassiveMountEffects_complete @ react-dom.development.js:24930
> commitPassiveMountEffects_begin @ react-dom.development.js:24917
> commitPassiveMountEffects @ react-dom.development.js:24905
> flushPassiveEffectsImpl @ react-dom.development.js:27078
> flushPassiveEffects @ react-dom.development.js:27023
> commitRootImpl @ react-dom.development.js:26974
> commitRoot @ react-dom.development.js:26721
> performSyncWorkOnRoot @ react-dom.development.js:26156
> flushSyncCallbacks @ react-dom.development.js:12042
> (anonymous) @ react-dom.development.js:25690

I’ve extracted all the relevant code related to the annotator so you can review it and see if there’s an issue on my end with the implementation.

Additionally, I’ve noticed that when storing shapes and then reusing them later, the shape IDs are not preserved. For example, if I save shapes with IDs 1, 2, and 3, when reloaded, they appear in annotator.getShapes() with new IDs, such as 34, 38, and 40. Would it be possible to add functionality to set and maintain shape IDs, especially when reconstructing them from a file?

As another side note, would it also be possible to add support for percentage-based dimensions in the annotator? Using the original size can be excessive for large images, and relying solely on pixels makes it difficult to adapt to different screen sizes.

```js
const { setHandles, annotator } = useImageAnnotator();
const [shapes, setShapes] = useState([]);
const [images, setImages] = useState([]);
const [curImgIdxCrop, setCurImgIdxCrop] = useState(0); // carrousel for images
const [currentField, setCurrentField] = useState(''); // selected field
const [allShapes, setAllShapes] = useState({});

const [divH, setDivH] = useState(null);
const [divW, setDivW] = useState(null);
const divv = useCallback(node => {
	if (node !== null) {
		setDivH(node.getBoundingClientRect().height);
		setDivW(node.getBoundingClientRect().width);
	}
}, []);

useEffect(() => {
	console.log(currentField);
	console.log(curImgIdxCrop);
	if (allShapes[currentField] && allShapes[currentField][curImgIdxCrop]) {
		setShapes(allShapes[currentField][curImgIdxCrop]);
	} else {
		setShapes([]);
	}
	// setKey(prevKey => prevKey + 1);
}, [currentField, curImgIdxCrop]);

const shapeDrawn = (
	shape,
	annotator,
	curImgIdxCrop,
	currentField,
	setAllShapes
) => {
	annotator.updateCategories(shape.id, [currentField]);
	const lastShape = annotator.getShapes().pop();
	setAllShapes(prevShapes => {
		const newShapes = { ...prevShapes };
		if (!newShapes[currentField]) {
			newShapes[currentField] = [];
		}
		if (!newShapes[currentField][curImgIdxCrop]) {
			newShapes[currentField][curImgIdxCrop] = [];
		}
		newShapes[currentField][curImgIdxCrop].push(lastShape);
		return newShapes;
	});
};

<ImageAnnotator
	// key={key}
	setHandles={setHandles}
	shapes={shapes}
	width={divW}
	height={divH}
	imageUrl={images[curImgIdxCrop]?.content || ''}
	onReady={annotator => {
		if (currentField) {
			annotator.drawRectangle();
		}
	}}
	onAdded={shape =>
		shapeDrawn(shape, annotator, curImgIdxCrop, currentField, setAllShapes)
	}
/>;
```

**Comment by Azadeh-Koohjani** [comment]
Based on your scenario, I created the following sample and I didn't have any bug or problem
1. I used three `useState`s:
```js
const [shapes, setShapes] = React.useState<Shape[]>([]);
const [allShapes, setAllShapes] = React.useState<Shape[]>([]);
const [cat, setCat] = useState('rectangle');
```
2. Then, I added 3 buttons (Rectangle, Circle, and Polygon) to select a category, filter `allShapes`, and set `shapes`:
```html
<button onClick={() => { setCat('rectangle'); setShapes(allShapes.filter(shape => shape.type === 'rectangle')); }}>Rectangle</button>
<button onClick={() => { setCat('circle'); setShapes(allShapes.filter(shape => shape.type === 'circle')); }}>Circle</button>
<button onClick={() => { setCat('polygon'); setShapes(allShapes.filter(shape => shape.type === 'polygon')); }}>Polygon</button>
```

3. Finally, I implemented 'onAdded' and 'onReady' as following:
```js
<ImageAnnotator
        …
        onAdded={shape => {
          annotator!.updateCategories(shape.id, shape.categories, "#0004");
          let _shape = annotator!.getShapes().find(s => s.id===shape.id)!;
          setAllShapes(all => ([...all, _shape]));
        }}
        onReady={annotator => {
          switch (cat) {
            case 'rectangle':
              annotator.drawRectangle();
              break;
            case 'circle':
              annotator.drawCircle();
              break;
            case 'polygon':
              annotator.drawPolygon();
              break;
          }
        }} />
```
` updateCategories` is only called to add color to the shape. You can just call `setAllShapes(all => ([...all, shape]))` in `onAdded`, if you do not need background color. If you don't understand how it works, please ask for a demo.
